In [2]:
%pip install pandas numpy scikit-learn matplotlib seaborn prophet

Collecting pandas
  Using cached pandas-2.2.3-cp313-cp313-macosx_11_0_arm64.whl.metadata (89 kB)
Collecting numpy
  Using cached numpy-2.2.0-cp313-cp313-macosx_14_0_arm64.whl.metadata (62 kB)
Collecting scikit-learn
  Using cached scikit_learn-1.6.0-cp313-cp313-macosx_12_0_arm64.whl.metadata (31 kB)
Collecting matplotlib
  Using cached matplotlib-3.9.4-cp313-cp313-macosx_11_0_arm64.whl.metadata (11 kB)
Collecting seaborn
  Using cached seaborn-0.13.2-py3-none-any.whl.metadata (5.4 kB)
Collecting prophet
  Using cached prophet-1.1.6-py3-none-macosx_11_0_arm64.whl.metadata (3.5 kB)
Requirement already satisfied: python-dateutil>=2.8.2 in /Users/jo/Desktop/kaggle-store-sales-forecasting/.venv/lib/python3.13/site-packages (from pandas) (2.9.0.post0)
Collecting pytz>=2020.1 (from pandas)
  Using cached pytz-2024.2-py2.py3-none-any.whl.metadata (22 kB)
Collecting tzdata>=2022.7 (from pandas)
  Using cached tzdata-2024.2-py2.py3-none-any.whl.metadata (1.4 kB)
Collecting scipy>=1.6.0 (from scikit-learn)
  Using cached scipy-1.14.1-cp313-cp313-macosx_14_0_arm64.whl.metadata (60 kB)
Collecting joblib>=1.2.0 (from scikit-learn)
  Using cached joblib-1.4.2-py3-none-any.whl.metadata (5.4 kB)
Collecting threadpoolctl>=3.1.0 (from scikit-learn)
  Using cached threadpoolctl-3.5.0-py3-none-any.whl.metadata (13 kB)
Collecting contourpy>=1.0.1 (from matplotlib)
  Using cached contourpy-1.3.1-cp313-cp313-macosx_11_0_arm64.whl.metadata (5.4 kB)
Collecting cycler>=0.10 (from matplotlib)
  Using cached cycler-0.12.1-py3-none-any.whl.metadata (3.8 kB)
Collecting fonttools>=4.22.0 (from matplotlib)
  Using cached fonttools-4.55.3-cp313-cp313-macosx_10_13_universal2.whl.metadata (165 kB)
Collecting kiwisolver>=1.3.1 (from matplotlib)
  Using cached kiwisolver-1.4.7-cp313-cp313-macosx_11_0_arm64.whl.metadata (6.3 kB)
Requirement already satisfied: packaging>=20.0 in /Users/jo/Desktop/kaggle-store-sales-forecasting/.venv/lib/python3.13/site-packages (from matplotlib) (24.2)
Collecting pillow>=8 (from matplotlib)
  Using cached pillow-11.0.0-cp313-cp313-macosx_11_0_arm64.whl.metadata (9.1 kB)
Collecting pyparsing>=2.3.1 (from matplotlib)
  Using cached pyparsing-3.2.0-py3-none-any.whl.metadata (5.0 kB)
Collecting cmdstanpy>=1.0.4 (from prophet)
  Using cached cmdstanpy-1.2.5-py3-none-any.whl.metadata (4.0 kB)
Collecting holidays<1,>=0.25 (from prophet)
  Using cached holidays-0.62-py3-none-any.whl.metadata (26 kB)
Collecting tqdm>=4.36.1 (from prophet)
  Using cached tqdm-4.67.1-py3-none-any.whl.metadata (57 kB)
Collecting importlib-resources (from prophet)
  Using cached importlib_resources-6.4.5-py3-none-any.whl.metadata (4.0 kB)
Collecting stanio<2.0.0,>=0.4.0 (from cmdstanpy>=1.0.4->prophet)
  Using cached stanio-0.5.1-py3-none-any.whl.metadata (1.6 kB)
Requirement already satisfied: six>=1.5 in /Users/jo/Desktop/kaggle-store-sales-forecasting/.venv/lib/python3.13/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Using cached pandas-2.2.3-cp313-cp313-macosx_11_0_arm64.whl (11.3 MB)
Using cached numpy-2.2.0-cp313-cp313-macosx_14_0_arm64.whl (5.1 MB)
Using cached scikit_learn-1.6.0-cp313-cp313-macosx_12_0_arm64.whl (11.1 MB)
Using cached matplotlib-3.9.4-cp313-cp313-macosx_11_0_arm64.whl (7.8 MB)
Downloading seaborn-0.13.2-py3-none-any.whl (294 kB)
Using cached prophet-1.1.6-py3-none-macosx_11_0_arm64.whl (8.2 MB)
Using cached cmdstanpy-1.2.5-py3-none-any.whl (94 kB)
Using cached contourpy-1.3.1-cp313-cp313-macosx_11_0_arm64.whl (255 kB)
Using cached cycler-0.12.1-py3-none-any.whl (8.3 kB)
Using cached fonttools-4.55.3-cp313-cp313-macosx_10_13_universal2.whl (2.8 MB)
Using cached holidays-0.62-py3-none-any.whl (1.2 MB)
Using cached joblib-1.4.2-py3-none-any.whl (301 kB)
Using cached kiwisolver-1.4.7-cp313-cp313-macosx_11_0_arm64.whl (63 kB)
Using cached pillow-11.0.0-cp313-cp313-macosx_11_0_arm64.whl (3.0 MB)
Using cached pyparsing-3.2.0-py3-none-any.whl (106 kB)
Using cached pytz-2024.2-py2.py3-none-any.whl (508 kB)
Using cached scipy-1.14.1-cp313-cp313-macosx_14_0_arm64.whl (23.1 MB)
Using cached threadpoolctl-3.5.0-py3-none-any.whl (18 kB)
Using cached tqdm-4.67.1-py3-none-any.whl (78 kB)
Using cached tzdata-2024.2-py2.py3-none-any.whl (346 kB)
Using cached importlib_resources-6.4.5-py3-none-any.whl (36 kB)
Using cached stanio-0.5.1-py3-none-any.whl (8.1 kB)
Installing collected packages: pytz, tzdata, tqdm, threadpoolctl, pyparsing, pillow, numpy, kiwisolver, joblib, importlib-resources, fonttools, cycler, stanio, scipy, pandas, holidays, contourpy, scikit-learn, matplotlib, cmdstanpy, seaborn, prophet
Successfully installed cmdstanpy-1.2.5 contourpy-1.3.1 cycler-0.12.1 fonttools-4.55.3 holidays-0.62 importlib-resources-6.4.5 joblib-1.4.2 kiwisolver-1.4.7 matplotlib-3.9.4 numpy-2.2.0 pandas-2.2.3 pillow-11.0.0 prophet-1.1.6 pyparsing-3.2.0 pytz-2024.2 scikit-learn-1.6.0 scipy-1.14.1 seaborn-0.13.2 stanio-0.5.1 threadpoolctl-3.5.0 tqdm-4.67.1 tzdata-2024.2
Note: you may need to restart the kernel to use updated packages.

In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score


from prophet import Prophet

ModuleNotFoundError: No module named 'pandas'

In [14]:
train = pd.read_feather('../Data/Processed/train.feather')
test = pd.read_feather('../Data/Processed/test.feather')

In [15]:
pd.set_option('display.max_columns', None)
train.head()

,id,date,sales,onpromotion,family_BABY CARE,family_BEAUTY,family_BEVERAGES,family_BOOKS,family_CELEBRATION,family_CLEANING,family_DAIRY,family_GROCERY I,family_GROCERY II,family_HARDWARE,family_HOME AND KITCHEN I,family_HOME AND KITCHEN II,family_HOME APPLIANCES,family_LADIESWEAR,family_LAWN AND GARDEN,family_LINGERIE,family_MAGAZINES,family_PET SUPPLIES,family_PLAYERS AND ELECTRONICS,family_PRODUCE,family_SCHOOL AND OFFICE SUPPLIES,family_SEAFOOD,holiday_Primer dia del ano,dcoilwtico,dcoilwtico_lag,dcoilwtico_lag_7,dcoilwtico_lag_30,city_Quito,state_Pichincha,type_C,cluster_3,cluster_5,cluster_8,cluster_11,cluster_14
0,0,2013-01-01,0.0,0,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,93.14,93.14,93.14,93.14,True,True,False,False,False,False,False,False
1,1,2013-01-01,0.0,0,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,93.14,93.14,93.14,93.14,True,True,False,False,False,False,False,False
2,2,2013-01-01,0.0,0,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,93.14,93.14,93.14,93.14,True,True,False,False,False,False,False,False
3,3,2013-01-01,0.0,0,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,93.14,93.14,93.14,93.14,True,True,False,False,False,False,False,False
4,4,2013-01-01,0.0,0,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,93.14,93.14,93.14,93.14,True,True,False,False,False,False,False,False

In [16]:
train

,id,date,sales,onpromotion,family_BABY CARE,family_BEAUTY,family_BEVERAGES,family_BOOKS,family_CELEBRATION,family_CLEANING,family_DAIRY,family_GROCERY I,family_GROCERY II,family_HARDWARE,family_HOME AND KITCHEN I,family_HOME AND KITCHEN II,family_HOME APPLIANCES,family_LADIESWEAR,family_LAWN AND GARDEN,family_LINGERIE,family_MAGAZINES,family_PET SUPPLIES,family_PLAYERS AND ELECTRONICS,family_PRODUCE,family_SCHOOL AND OFFICE SUPPLIES,family_SEAFOOD,holiday_Primer dia del ano,dcoilwtico,dcoilwtico_lag,dcoilwtico_lag_7,dcoilwtico_lag_30,city_Quito,state_Pichincha,type_C,cluster_3,cluster_5,cluster_8,cluster_11,cluster_14
0,0,2013-01-01,0.000,0,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,93.14,93.14,93.14,93.140000,True,True,False,False,False,False,False,False
1,1,2013-01-01,0.000,0,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,93.14,93.14,93.14,93.140000,True,True,False,False,False,False,False,False
2,2,2013-01-01,0.000,0,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,93.14,93.14,93.14,93.140000,True,True,False,False,False,False,False,False
3,3,2013-01-01,0.000,0,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,93.14,93.14,93.14,93.140000,True,True,False,False,False,False,False,False
4,4,2013-01-01,0.000,0,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,93.14,93.14,93.14,93.140000,True,True,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3000883,3000883,2017-08-15,438.133,0,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,47.57,47.59,49.57,45.413333,True,True,False,False,False,False,False,False
3000884,3000884,2017-08-15,154.553,1,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,47.57,47.59,49.57,45.413333,True,True,False,False,False,False,False,False
3000885,3000885,2017-08-15,2419.729,148,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,47.57,47.59,49.57,45.413333,True,True,False,False,False,False,False,False
3000886,3000886,2017-08-15,121.000,8,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,47.57,47.59,49.57,45.413333,True,True,False,False,False,False,False,False
3000887,3000887,2017-08-15,16.000,0,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,47.57,47.59,49.57,45.413333,True,True,False,False,False,False,False,False

In [ ]:
train_prophet = train.rename(columns={'date': 'ds', 'sales': 'y'})

X_train, X_test, y_train, y_test = train_test_split(train_prophet[['ds']], train_prophet['y'], test_size=0.2, random_state=42)

model = Prophet()

train_data = pd.DataFrame({'ds': X_train['ds'], 'y': y_train})

model.fit(train_data)

test_data = pd.DataFrame({'ds': X_test['ds']})

forecast = model.predict(test_data)

09:02:14 - cmdstanpy - INFO - Chain [1] start processing
09:07:42 - cmdstanpy - INFO - Chain [1] done processing